---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kyma-demo
    kyma-grafana: enabled
  name: kyma-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kyma-demo
        kyma-grafana: enabled
    spec:
      containers:
        - image: eugen1993/kyma-demo:1
          name: kyma-demo
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: kyma-demo
                optional: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kyma-demo
  name: kyma-demo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kyma-demo
  type: ClusterIP
status:
  loadBalancer: {}
